# Generated by Django 3.1.6 on 2021-02-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('mob_no', models.IntegerField()),
                ('stclass', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
